# CONFIG

In [131]:
import polars as pl
import sqlite3
import tomllib
import glob
import numpy as np

In [2]:
from datetime import datetime
import os

In [3]:
import paramiko
from scp import SCPClient

In [4]:
with open("secrets.toml", "rb") as f:
    config = tomllib.load(f)
creds = config["mikrus"]

In [5]:
TABLES = ["offers", "offers_tytan", "offers_gralczyk", "offers_polnoc", "analyzed_offers" ]

In [6]:
pl.Config.set_tbl_rows(10)
pl.Config.STR_SET_ELIDED_BOUND = 500 
pl.Config.TT_CHOP_STR_BOUND = 500     
pl.Config.TABLE_WIDTH = 1000     
pl.Config.set_fmt_str_lengths(1000)

polars.config.Config

In [7]:
CITIES_GEO = {
    'ELŻBIECIN': {'lat': 53.1672, 'lon': 22.1231},
    'ZAMBRÓW': {'lat': 52.9856, 'lon': 22.2428},
    'STARE ZAKRZEWO': {'lat': 53.0042, 'lon': 22.2983},
    'PUPKI': {'lat': 53.2258, 'lon': 21.8497},
    'WYGODA': {'lat': 53.1022, 'lon': 22.1481},
    'STARE MODZELE': {'lat': 53.1114, 'lon': 22.3164},
    'NOWOGRÓD': {'lat': 53.2264, 'lon': 21.8806},
    'CZERWONE': {'lat': 53.4336, 'lon': 21.9044},
    'JANKI STARE': {'lat': 52.9419, 'lon': 22.4278},
    'GRĄDY': {'lat': 53.1158, 'lon': 22.1158},
    'CZACHY': {'lat': 53.0453, 'lon': 22.3456},
    'GROCHY': {'lat': 52.9461, 'lon': 22.3614},
    'DROZDOWO': {'lat': 53.1492, 'lon': 22.1644},
    'DĄBEK': {'lat': 53.0414, 'lon': 21.4647},
    'OSTROŁĘKA': {'lat': 53.0842, 'lon': 21.5731},
    'SIEMIEŃ NADRZECZNY': {'lat': 53.1978, 'lon': 22.1853},
    'SZLASY': {'lat': 53.0614, 'lon': 22.0647},
    'GRZYMAŁY SZCZEPANKOWSKIE': {'lat': 53.1436, 'lon': 21.9892},
    'CZERWIN': {'lat': 52.9239, 'lon': 21.6442},
    'FILOCHY': {'lat': 52.9481, 'lon': 21.7258},
    'KISIOŁKI': {'lat': 53.1667, 'lon': 22.3333},
    'BALIKI': {'lat': 53.2847, 'lon': 21.8594},
    'JANOWO': {'lat': 53.4864, 'lon': 21.9069},
    'SZUMOWO': {'lat': 52.9153, 'lon': 22.0736},
    'STARA ŁOMŻA PRZY SZOSIE': {'lat': 53.1603, 'lon': 22.0944},
    'NOWY CYDZYN': {'lat': 53.2753, 'lon': 22.1764},
    'STARE BOŻEJEWO': {'lat': 53.2383, 'lon': 22.3486},
    'DŁUGI KĄT': {'lat': 53.3308, 'lon': 21.7375},
    'ZAWADY': {'lat': 53.1539, 'lon': 22.6653},
    'MIASTKOWO': {'lat': 53.1489, 'lon': 21.8211},
    'KSIĘŻOPOLE': {'lat': 52.3306, 'lon': 22.2547},
    'JEDWABNE': {'lat': 53.2861, 'lon': 22.3019},
    'NOWE KUPISKI': {'lat': 53.1975, 'lon': 21.9844},
    'TRUSZKI': {'lat': 53.3236, 'lon': 22.1158},
    'ŚWIDRY': {'lat': 53.1561, 'lon': 21.9056},
    'SASINY': {'lat': 52.6186, 'lon': 22.9511},
    'WYSOKIE MAŁE': {'lat': 53.2681, 'lon': 22.1156},
    'WIZNA': {'lat': 53.1931, 'lon': 22.3831},
    'RUTKI': {'lat': 53.1000, 'lon': 22.4167},
    'SIEMNOCHA': {'lat': 53.2458, 'lon': 22.0833},
    'NAGÓRKI': {'lat': 53.1581, 'lon': 22.3333},
    'CZAPLICE': {'lat': 53.1114, 'lon': 22.1258},
    'MROCZKI': {'lat': 52.9983, 'lon': 22.3364},
    'JURZEC WŁOŚCIAŃSKI': {'lat': 53.3000, 'lon': 22.2167},
    'KOLNO': {'lat': 53.4131, 'lon': 21.9322},
    'STARE RATOWO': {'lat': 53.0114, 'lon': 21.8456},
    'KRUSZA': {'lat': 53.0781, 'lon': 21.5031},
    'GRODZISK DUŻY': {'lat': 52.4833, 'lon': 22.7500},
    'OJCEWO': {'lat': 53.3364, 'lon': 22.2542},
    'BACZE SUCHE': {'lat': 53.0564, 'lon': 22.1647},
    'GOSIE MAŁE': {'lat': 53.0244, 'lon': 22.4214},
    'JABŁONKA': {'lat': 53.5358, 'lon': 21.5061},
    'POPIOŁKI': {'lat': 53.3642, 'lon': 21.8597},
    'DRWĘCZ': {'lat': 53.0647, 'lon': 21.6642},
    'PODGÓRZE': {'lat': 53.1203, 'lon': 22.1236},
    'RZEKUŃ': {'lat': 53.0561, 'lon': 21.6167},
    'STARA ŁOMŻA NAD RZEKĄ': {'lat': 53.1656, 'lon': 22.1128},
    'SZCZEPANKOWO': {'lat': 53.1167, 'lon': 21.9833},
    'JARNUTY': {'lat': 53.1167, 'lon': 21.6833},
    'TUROŚL': {'lat': 53.3853, 'lon': 21.7258},
    'STARE KUPISKI': {'lat': 53.1972, 'lon': 21.9964},
    'KUPISKI STARE': {'lat': 53.1972, 'lon': 21.9964},
    'DŁUGOBÓRZ PIERWSZY': {'lat': 52.9667, 'lon': 22.2167},
    'WIKTORZYN': {'lat': 52.8833, 'lon': 21.7500},
    'KACZYNEK': {'lat': 53.0114, 'lon': 21.6831},
    'RYBAKI': {'lat': 53.1842, 'lon': 22.3164},
    'SAMBORY': {'lat': 53.2258, 'lon': 22.3853},
    'LELIS': {'lat': 53.1592, 'lon': 21.5644},
    'RUDKA': {'lat': 52.7333, 'lon': 22.7333},
    'KRAJEWO': {'lat': 52.9833, 'lon': 22.3333},
    'WYŁUDZIN': {'lat': 53.2458, 'lon': 21.7258},
    'LASKI SZLACHECKIE': {'lat': 52.9414, 'lon': 21.4647},
    'RYDZEWO': {'lat': 53.3086, 'lon': 22.0647},
    'SULĘCIN SZLACHECKI': {'lat': 52.8464, 'lon': 21.9167},
    'PIĄTNICA PODUCHOWNA': {'lat': 53.1894, 'lon': 22.0919},
    'BARTKI': {'lat': 53.3414, 'lon': 21.5258},
    'KORYTKI LEŚNE': {'lat': 53.1333, 'lon': 21.9500},
    'OSTROŻNE': {'lat': 52.9833, 'lon': 22.1167},
    'PROSIENICA': {'lat': 52.9167, 'lon': 21.9500},
    'STARY CYDZYN': {'lat': 53.2753, 'lon': 22.1856},
    'JURKI': {'lat': 53.3983, 'lon': 22.1114},
    'DOBRY LAS': {'lat': 53.3167, 'lon': 21.8333},
    'LACHOWO': {'lat': 53.4667, 'lon': 22.0167},
    'GOSTERY': {'lat': 53.0333, 'lon': 21.8667},
    'STARE KRAJEWO': {'lat': 52.9833, 'lon': 22.3500},
    'STARY LUBOTYŃ': {'lat': 52.9167, 'lon': 21.8833},
    'BORKOWO': {'lat': 53.2986, 'lon': 21.9142},
    'MOCARZE': {'lat': 53.2758, 'lon': 22.4258},
    'TABĘDZ': {'lat': 53.0333, 'lon': 22.1667},
    'JEZIORKO': {'lat': 53.2281, 'lon': 22.1456},
    'ŁAWY': {'lat': 53.0667, 'lon': 21.6167},
    'ŁOCHTYNOWO': {'lat': 53.1667, 'lon': 22.0333},
    'WOLA ZAMBROWSKA': {'lat': 52.9667, 'lon': 22.2500},
    'LASKOWIEC': {'lat': 53.0833, 'lon': 21.5333},
    'GIEŁCZYN': {'lat': 53.1114, 'lon': 22.0542},
    'PORYTE': {'lat': 53.3258, 'lon': 22.0831},
    'ŁOMŻA': {'lat': 53.1781, 'lon': 22.0592},
    'TROSZYN': {'lat': 53.0333, 'lon': 21.7333},
    'MOTYKA': {'lat': 53.1667, 'lon': 21.8833},
    'PIANKI': {'lat': 53.2167, 'lon': 22.0167},
    'KISIELNICA': {'lat': 53.2286, 'lon': 22.0542},
    'KONOPKI': {'lat': 53.0667, 'lon': 22.3167},
    'BURZYN': {'lat': 53.2758, 'lon': 22.4647},
    'KOSAKI': {'lat': 53.1667, 'lon': 22.2833},
    'KĄTY': {'lat': 53.3167, 'lon': 22.1667},
    'RATOWO': {'lat': 53.0167, 'lon': 21.8333},
    'PNIEWO': {'lat': 53.1167, 'lon': 22.0833},
    'KOŁAKI KOŚCIELNE': {'lat': 53.0167, 'lon': 22.3667},
    'BUDY CZARNOCKIE': {'lat': 53.2167, 'lon': 22.1500},
    'KOWNATY': {'lat': 53.2667, 'lon': 22.2167},
    'OSETNO': {'lat': 53.6833, 'lon': 19.8667},
    'MIKOŁAJKI': {'lat': 53.8014, 'lon': 21.5714},
    'KONARZYCE': {'lat': 53.1333, 'lon': 22.0500},
    'JEDNACZEWO': {'lat': 53.2081, 'lon': 21.9542},
    'PRZYTUŁY': {'lat': 53.3667, 'lon': 22.3167},
    'GOŁASZE': {'lat': 52.9833, 'lon': 22.5000},
    'KRZEWO': {'lat': 53.1500, 'lon': 22.3667},
    'STARY GROMADZYN': {'lat': 53.4000, 'lon': 21.9167},
    'KARWOWO': {'lat': 53.2667, 'lon': 22.3833},
    'OBRYTKI': {'lat':	53.3687798,'lon':22.2742335},
    'ZABAWKA': {'lat' :53.1995772, 'lon': 22.1571153},
    'SIEBURCZYN': 	{ 'lat' : 53.2414279, 'lon' : 22.4342496},
    'SZÓSTAKI' : { 'lat' :53.2833309, 'lon' : 22.4569495},
    'GÓRKI-SYPNIEWO' : { 'lat' : 53.273853, 'lon' : 22.1353291},
    'ŚNIADOWO': 	{'lat':53.0386233, 'lon':21.9902764},
    'SIESTRZANKI': { 'lat':53.306823, 'lon': 22.4139482},
    'BUDY MIKOłAJKA': { 'lat': 53.255353, 'lon' : 22.1711752},
    'MODZELE SKUDOSZE': { 'lat' : 53.0550814, 'lon': 22.1775928},
    'PIĄTNICA WŁOŚCIAŃSKA': { 'lat' :53.1859359, 'lon': 22.1050388},
    'RZADKOWO': {'lat':53.2219677, 'lon':22.143627},
    'PIĄTNICA' : {'lat':53.21542775, 'lon':22.177244553669112},
    'ZOSIN' : {'lat': 53.141755, 'lon': 22.1116481},
    'MORGOWNIKI': {'lat': 53.2275, 'lon': 21.8903},       
    'JANÓW': {'lat': 53.1558, 'lon': 22.1353},            
    'JĘCZNIKI': {'lat': 53.5358, 'lon': 20.9414},         
    'WYK': {'lat': 53.2758, 'lon': 21.9058},              
    'PTAKI': {'lat': 53.3058, 'lon': 21.8481},           
    'ZBÓJNA': {'lat': 53.2358, 'lon': 21.8153},          
    'BUDNE': {'lat': 53.3342, 'lon': 22.4286},            
    'NOWY KRZEW': {'lat': 53.1158, 'lon': 22.2542},       
    'KOZIOŁ': {'lat': 53.4258, 'lon': 21.8986},          
    'MIASTKOWO': {'lat': 53.1508, 'lon': 21.8386},        
    'DĘBOWO': {'lat': 53.6058, 'lon': 22.9253},           
    'BUDY KRANOCKIE': {'lat': 53.1958, 'lon': 22.1486},  
    'STARA ŁOMŻA': {'lat': 53.1658, 'lon': 22.0986},  
    'STAREJ ŁOMŻY': {'lat': 53.1658, 'lon': 22.0986},
    'SIEMIĘ NADRZECZNE': {'lat': 53.1858, 'lon': 22.0253}, 
    'WYRZYKI': {'lat': 53.1058, 'lon': 22.1553},
    'ROGIENICE WIELKIE': {'lat':53.1616, 'lon':22.044},
    'KOBYLIN': {'lat':53.293171789627955, 'lon': 22.14513394107225,}
}

# HELPER FUNCTIONS

In [8]:
def download_db():
    now = datetime.now().strftime("%Y-%m-%d")
    folder_name = "db"
    
    if not os.path.exists(folder_name):
        os.makedirs(folder_name)
    
    local_filename = f"{now}_olx.db"
    local_full_path = os.path.join(folder_name, local_filename)

    print(f"Connecting {creds['host']}...")
    
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    try:
        ssh.connect(
            hostname=creds["host"],
            port=creds["port"],
            username=creds["user"],
            password=creds["password"]
        )
        
        with SCPClient(ssh.get_transport()) as scp:
            print(f"Pobieranie {creds['remote_path']} -> {local_full_path}")
            scp.get(creds["remote_path"], local_full_path)
            
        print(f"Database saved as: {local_full_path}")
        return local_full_path  
        
    except Exception as e:
        print(f"Error: {e}")
        return None
    finally:
        ssh.close()

In [9]:
def get_latest_db_path(folder="db"):
    files = glob.glob(os.path.join(folder, "*.db"))
    
    if not files:
        print("Not found file with extension 'db'!")
        return None
    
    latest_file = max(files)
    print(f"newest file: {latest_file}")
    return latest_file

In [10]:
def load_data_to_df(db_name: str, table_name: str) -> pl.DataFrame | None:
    conn = None
    try:
        conn = sqlite3.connect(db_name)
        print(f"DB connected: {db_name}")

        query = f"SELECT * FROM {table_name}"
        df = pl.read_database(query, conn)

        print(f"DF loaded: {table_name}")
        print(f"DF shape: {df.shape}")
        return df

    except sqlite3.Error as e:
        print(f"SQLite error: {e}")
        return None
    except Exception as e:
        print(f"Error: {e}")
        return None
    finally:
        if conn:
            conn.close()
            print("DB connection closed.")

In [11]:
def simplify_text(text: str) -> str:
    trans = str.maketrans("ĄĆĘŁŃÓŚŹŻ", "ACELNOSZZ")
    return text.upper().translate(trans)

In [135]:
def add_haversine_distance(df, target_lat, target_lon):
    R = 6371.0
    lat1 = target_lat * np.pi / 180
    lon1 = target_lon * np.pi / 180

    return df.with_columns(
        (
            2 * R * (
                (
                    ((pl.col("LAT") * np.pi / 180 - lat1) / 2).sin()**2 +
                    pl.lit(np.cos(lat1)) * (pl.col("LAT") * np.pi / 180).cos() * ((pl.col("LON") * np.pi / 180 - lon1) / 2).sin()**2
                ).sqrt().arcsin()
            )
        ).cast(pl.Float64).alias("MAIN_CITY_DIST") 
    )

# DOWNLOADING DATA

In [12]:
download_db()

Connecting jan154.mikrus.xyz...
Pobieranie /root/Estate_scrapper/olx.db -> db\2026-03-15_olx.db
Database saved as: db\2026-03-15_olx.db

'db\\2026-03-15_olx.db'

In [13]:
DB_NAME = get_latest_db_path()

newest file: db\2026-03-15_olx.db

In [14]:
data = {}

In [15]:
for TABLE in TABLES:
    data[TABLE] = load_data_to_df(DB_NAME, TABLE)

DB connected: db\2026-03-15_olx.db
DF loaded: offers
DF shape: (320, 12)
DB connection closed.
DB connected: db\2026-03-15_olx.db
DF loaded: offers_tytan
DF shape: (47, 9)
DB connection closed.
DB connected: db\2026-03-15_olx.db
DF loaded: offers_gralczyk
DF shape: (32, 26)
DB connection closed.
DB connected: db\2026-03-15_olx.db
DF loaded: offers_polnoc
DF shape: (108, 30)
DB connection closed.
DB connected: db\2026-03-15_olx.db
DF loaded: analyzed_offers
DF shape: (40135, 12)
DB connection closed.

In [16]:
data.keys()

dict_keys(['offers', 'offers_tytan', 'offers_gralczyk', 'offers_polnoc', 'analyzed_offers'])

# Data processing

## OLX ("offers")

In [17]:
data["offers"].head()

shape: (5, 12)
┌────────────────┬───────────────┬───────────────┬─────────┬───┬───────────┬───────────────┬──────────────┬────────────┐
│ ID             ┆ TEXT          ┆ LINK          ┆ VALUE   ┆ … ┆ CITY      ┆ DATE_ORIG     ┆ LAST_UPDATED ┆ DATE_ISO   │
│ ---            ┆ ---           ┆ ---           ┆ ---     ┆   ┆ ---       ┆ ---           ┆ ---          ┆ ---        │
│ str            ┆ str           ┆ str           ┆ i64     ┆   ┆ str       ┆ str           ┆ str          ┆ str        │
╞════════════════╪═══════════════╪═══════════════╪═════════╪═══╪═══════════╪═══════════════╪══════════════╪════════════╡
│ Łomża_2134_990 ┆ Działka na    ┆ https://www.o ┆ 99000   ┆ … ┆ Łomża     ┆ Łomża - 10    ┆ 2025-11-11   ┆ 2025-11-10 │
│ 00             ┆ sprzedaż z    ┆ todom.pl/pl/o ┆         ┆   ┆           ┆ listopada     ┆              ┆            │
│                ┆ dostępem do   ┆ ferta/dzialka ┆         ┆   ┆           ┆ 2025          ┆              ┆            │
│                ┆ asfaltu i     ┆ -na-sprzedaz- ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ lasu99 000    ┆ z-dostepem-do ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ złŁomża - 10  ┆ -asfaltu-i-la ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ listopada     ┆ su-ID4yVmd.ht ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 20252 134 m²  ┆ ml            ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ - 46.39       ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ zł/m²Obserwuj ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│ Zawady_1000_13 ┆ Sprzedam      ┆ /d/oferta/spr ┆ 130000  ┆ … ┆ Zawady    ┆ Zawady - 11   ┆ 2025-11-11   ┆ 2026-02-11 │
│ 0000           ┆ działkę.      ┆ zedam-dzialke ┆         ┆   ┆           ┆ lutego 2026   ┆              ┆            │
│                ┆ Elżbiecin.130 ┆ -elzbiecin-CI ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 000 złZawady  ┆ D3-ID11ZDLY.h ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ - 09          ┆ tml           ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ listopada     ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 20251 000 m²  ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ - 130         ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ zł/m²Obserwuj ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│ Elżbiecin_1220 ┆ Działka na    ┆ /d/oferta/dzi ┆ 1490000 ┆ … ┆ Elżbiecin ┆ Elżbiecin -   ┆ 2025-11-11   ┆ 2026-02-10 │
│ 0_1490000      ┆ sprzedaż1 490 ┆ alka-na-sprze ┆         ┆   ┆           ┆ 10 lutego     ┆              ┆            │
│                ┆ 000           ┆ daz-CID3-ID11 ┆         ┆   ┆           ┆ 2026          ┆              ┆            │
│                ┆ złElżbiecin - ┆ ZvRU.html     ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 09 listopada  ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 202512 200 m² ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ - 122.13      ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ zł/m²Obserwuj ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│ Jurki_3000_675 ┆ Sprzedam      ┆ /d/oferta/spr ┆ 67500   ┆ … ┆ Jurki     ┆ Jurki - 06    ┆ 2025-11-11   ┆ 2025-11-06 │
│ 00             ┆ piękną dużą   ┆ zedam-piekna- ┆         ┆   ┆           ┆ listopada     ┆              ┆            │
│                ┆ 1200m2        ┆ duza-1200m2-d ┆         ┆   ┆           ┆ 2025          ┆              ┆            │
│                ┆ działkę przy  ┆ zialke-przy-r ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ rzece Pisie,  ┆ zece-pisie-w- ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ w Jurkach.67  ┆ jurkach-CID3- ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 500 złJurki - ┆ IDH8Ttm.html  ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 06 listopada  ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 20253 000 m²  ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ - 22.5        ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ zł/m²Obserwuj ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│ Łomża_1000_129 ┆ Sprzedam      ┆ /d/oferta/spr ┆ 129500  ┆ … ┆ Łomża     ┆ Łomża - 06    ┆ 2025-11-11   ┆ 2025-11-06 │
│ 500            ┆ działki pod   ┆ zedam-dzialki ┆         ┆   ┆           ┆ listopada     ┆              ┆            │
│                ┆ zabudowę      ┆ -pod-zabudowe ┆         ┆   ┆           ┆ 2025          ┆              ┆            │
│                ┆ mieszkaniową  ┆ -mieszkaniowa ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ jednorodzinną ┆ -jednorodzinn ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ w             ┆ a-w-gielczyni ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ Giełczynie129 ┆ e-CID3-IDZoZk ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 500 złŁomża - ┆ x.html        ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 06 listopada  ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ 20251 000 m²  ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ - 129.5       ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
│                ┆ zł/m²Obserwuj ┆               ┆         ┆   ┆           ┆               ┆              ┆            │
└────────────────┴───────────────┴───────────────┴─────────┴───┴───────────┴───────────────┴──────────────┴────────────┘

In [18]:
data["offers"] = data["offers"].rename({"DATE_ISO":"DATE_ADDED"})

In [19]:
data["offers"] = data["offers"].with_columns(
    pl.col(["LAST_UPDATED", "DATE_ADDED"]).str.to_date(format="%Y-%m-%d")
            )

In [20]:
data["offers"] = data["offers"].with_columns(
    pl.col(["AREA_M2", "PRICE_M2"]).cast(pl.Float64)
)

In [21]:
data["offers"] = data["offers"].with_columns(
    pl.col("CITY").str.to_uppercase()
)

In [22]:
geo_df = pl.DataFrame([
    {"CITY": k, "LAT": v["lat"], "LON": v["lon"]} 
    for k, v in CITIES_GEO.items()
])

data["offers"] = data["offers"].join(geo_df, on="CITY", how="left")

In [23]:
print(data["offers"].null_count())

shape: (1, 14)
┌─────┬──────┬──────┬───────┬───┬──────────────┬────────────┬─────┬─────┐
│ ID  ┆ TEXT ┆ LINK ┆ VALUE ┆ … ┆ LAST_UPDATED ┆ DATE_ADDED ┆ LAT ┆ LON │
│ --- ┆ ---  ┆ ---  ┆ ---   ┆   ┆ ---          ┆ ---        ┆ --- ┆ --- │
│ u32 ┆ u32  ┆ u32  ┆ u32   ┆   ┆ u32          ┆ u32        ┆ u32 ┆ u32 │
╞═════╪══════╪══════╪═══════╪═══╪══════════════╪════════════╪═════╪═════╡
│ 0   ┆ 0    ┆ 0    ┆ 0     ┆ … ┆ 0            ┆ 3          ┆ 0   ┆ 0   │
└─────┴──────┴──────┴───────┴───┴──────────────┴────────────┴─────┴─────┘

In [24]:
data["offers"] = data["offers"].with_columns(pl.col("DATE_ADDED").fill_null(pl.col("LAST_UPDATED"))
)

In [25]:
data["offers"] = data["offers"].with_columns(
    pl.col("DATE_ADDED").dt.strftime("%A").alias("DAY_NAME_EN")
)

In [26]:
data["offers"].head(5)

shape: (5, 15)
┌───────────────────┬──────────────────┬──────────────────┬─────────┬───┬────────────┬─────────┬─────────┬─────────────┐
│ ID                ┆ TEXT             ┆ LINK             ┆ VALUE   ┆ … ┆ DATE_ADDED ┆ LAT     ┆ LON     ┆ DAY_NAME_EN │
│ ---               ┆ ---              ┆ ---              ┆ ---     ┆   ┆ ---        ┆ ---     ┆ ---     ┆ ---         │
│ str               ┆ str              ┆ str              ┆ i64     ┆   ┆ date       ┆ f64     ┆ f64     ┆ str         │
╞═══════════════════╪══════════════════╪══════════════════╪═════════╪═══╪════════════╪═════════╪═════════╪═════════════╡
│ Łomża_2134_99000  ┆ Działka na       ┆ https://www.otod ┆ 99000   ┆ … ┆ 2025-11-10 ┆ 53.1781 ┆ 22.0592 ┆ Monday      │
│                   ┆ sprzedaż z       ┆ om.pl/pl/oferta/ ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ dostępem do      ┆ dzialka-na-sprze ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ asfaltu i lasu99 ┆ daz-z-dostepem-d ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 000 złŁomża - 10 ┆ o-asfaltu-i-lasu ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ listopada 20252  ┆ -ID4yVmd.html    ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 134 m² - 46.39   ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ zł/m²Obserwuj    ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│ Zawady_1000_13000 ┆ Sprzedam         ┆ /d/oferta/sprzed ┆ 130000  ┆ … ┆ 2026-02-11 ┆ 53.1539 ┆ 22.6653 ┆ Wednesday   │
│ 0                 ┆ działkę.         ┆ am-dzialke-elzbi ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ Elżbiecin.130    ┆ ecin-CID3-ID11ZD ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 000 złZawady -   ┆ LY.html          ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 09 listopada     ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 20251 000 m² -   ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 130              ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ zł/m²Obserwuj    ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│ Elżbiecin_12200_1 ┆ Działka na       ┆ /d/oferta/dzialk ┆ 1490000 ┆ … ┆ 2026-02-10 ┆ 53.1672 ┆ 22.1231 ┆ Tuesday     │
│ 490000            ┆ sprzedaż1 490    ┆ a-na-sprzedaz-CI ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 000 złElżbiecin  ┆ D3-ID11ZvRU.html ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ - 09 listopada   ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 202512 200 m² -  ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 122.13           ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ zł/m²Obserwuj    ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│ Jurki_3000_67500  ┆ Sprzedam piękną  ┆ /d/oferta/sprzed ┆ 67500   ┆ … ┆ 2025-11-06 ┆ 53.3983 ┆ 22.1114 ┆ Thursday    │
│                   ┆ dużą 1200m2      ┆ am-piekna-duza-1 ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ działkę przy     ┆ 200m2-dzialke-pr ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ rzece Pisie, w   ┆ zy-rzece-pisie-w ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ Jurkach.67 500   ┆ -jurkach-CID3-ID ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ złJurki - 06     ┆ H8Ttm.html       ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ listopada 20253  ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 000 m² - 22.5    ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ zł/m²Obserwuj    ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│ Łomża_1000_129500 ┆ Sprzedam działki ┆ /d/oferta/sprzed ┆ 129500  ┆ … ┆ 2025-11-06 ┆ 53.1781 ┆ 22.0592 ┆ Thursday    │
│                   ┆ pod zabudowę     ┆ am-dzialki-pod-z ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ mieszkaniową     ┆ abudowe-mieszkan ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ jednorodzinną w  ┆ iowa-jednorodzin ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ Giełczynie129    ┆ na-w-gielczynie- ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 500 złŁomża - 06 ┆ CID3-IDZoZkx.htm ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ listopada 20251  ┆ l                ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ 000 m² - 129.5   ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
│                   ┆ zł/m²Obserwuj    ┆                  ┆         ┆   ┆            ┆         ┆         ┆             │
└───────────────────┴──────────────────┴──────────────────┴─────────┴───┴────────────┴─────────┴─────────┴─────────────┘

In [27]:
data["offers"].null_count()

shape: (1, 15)
┌─────┬──────┬──────┬───────┬───┬────────────┬─────┬─────┬─────────────┐
│ ID  ┆ TEXT ┆ LINK ┆ VALUE ┆ … ┆ DATE_ADDED ┆ LAT ┆ LON ┆ DAY_NAME_EN │
│ --- ┆ ---  ┆ ---  ┆ ---   ┆   ┆ ---        ┆ --- ┆ --- ┆ ---         │
│ u32 ┆ u32  ┆ u32  ┆ u32   ┆   ┆ u32        ┆ u32 ┆ u32 ┆ u32         │
╞═════╪══════╪══════╪═══════╪═══╪════════════╪═════╪═════╪═════════════╡
│ 0   ┆ 0    ┆ 0    ┆ 0     ┆ … ┆ 0          ┆ 0   ┆ 0   ┆ 0           │
└─────┴──────┴──────┴───────┴───┴────────────┴─────┴─────┴─────────────┘

In [28]:
data["offers"].filter(pl.col("LAT").is_null())["CITY"].unique().to_list()

[]

## TYTAN

In [29]:
data["offers_tytan"].head(2)

shape: (2, 9)
┌──────────────────┬──────────┬─────────────────┬─────────┬───┬──────────┬─────────────────┬──────────────┬────────────┐
│ ID               ┆ LOCATION ┆ NAME            ┆ AREA_M2 ┆ … ┆ PRICE_M2 ┆ LINK            ┆ LAST_UPDATED ┆ DATE_ADDED │
│ ---              ┆ ---      ┆ ---             ┆ ---     ┆   ┆ ---      ┆ ---             ┆ ---          ┆ ---        │
│ str              ┆ str      ┆ str             ┆ i64     ┆   ┆ f64      ┆ str             ┆ str          ┆ str        │
╞══════════════════╪══════════╪═════════════════╪═════════╪═══╪══════════╪═════════════════╪══════════════╪════════════╡
│ Szóstaki_18800_7 ┆ Szóstaki ┆ Działka rolna   ┆ 18800   ┆ … ┆ 4.0      ┆ https://tytan-n ┆ 2026-03-14   ┆ 2025-11-16 │
│ 5000             ┆          ┆ na terenie      ┆         ┆   ┆          ┆ ieruchomosci.co ┆              ┆            │
│                  ┆          ┆ Parku           ┆         ┆   ┆          ┆ m/nieruchomosci ┆              ┆            │
│                  ┆          ┆ Narodowego.     ┆         ┆   ┆          ┆ /?f_sectionName ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ 1=Lot&f_section ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ Name2=Sale&f_lo ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ cation_locality ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ [0]=&mapa=&mapa ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ X1=&mapaY1=&map ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ aX2=&mapaY2=&ma ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ paCX=&mapaCY=&m ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ apaCZ=0&mapaVis ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ =0&submit=Szuka ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ j&f_price_amoun ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ tMin=&f_price_a ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ mountMax=&f_tot ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ alAreaMin=&f_to ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ talAreaMax=&off ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ set_22934=0&cid ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ =22934/dzialka- ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ sprzedaz-188m2- ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ 75000pln-szosta ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ ki-podlaskie,15 ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ 77/18682/OGS    ┆              ┆            │
│ Szóstaki_7700_58 ┆ Szóstaki ┆ Działka rolna   ┆ 7700    ┆ … ┆ 7.0      ┆ https://tytan-n ┆ 2026-03-14   ┆ 2025-11-16 │
│ 000              ┆          ┆ Szostaki gmina  ┆         ┆   ┆          ┆ ieruchomosci.co ┆              ┆            │
│                  ┆          ┆ Jedwabne.       ┆         ┆   ┆          ┆ m/nieruchomosci ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ /?f_sectionName ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ 1=Lot&f_section ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ Name2=Sale&f_lo ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ cation_locality ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ [0]=&mapa=&mapa ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ X1=&mapaY1=&map ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ aX2=&mapaY2=&ma ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ paCX=&mapaCY=&m ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ apaCZ=0&mapaVis ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ =0&submit=Szuka ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ j&f_price_amoun ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ tMin=&f_price_a ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ mountMax=&f_tot ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ alAreaMin=&f_to ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ talAreaMax=&off ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ set_22934=0&cid ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ =22934/dzialka- ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ sprzedaz-077m2- ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ 58000pln-szosta ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ ki-podlaskie,15 ┆              ┆            │
│                  ┆          ┆                 ┆         ┆   ┆          ┆ 76/18682/OGS    ┆              ┆            │
└──────────────────┴──────────┴─────────────────┴─────────┴───┴──────────┴─────────────────┴──────────────┴────────────┘

In [30]:
data["offers_tytan"] = data["offers_tytan"].with_columns(
    pl.col(["LAST_UPDATED", "DATE_ADDED"]).str.to_date(format="%Y-%m-%d")
            )

In [31]:
data["offers_tytan"] = data["offers_tytan"].rename({"LOCATION":"CITY"})

In [32]:
data["offers_tytan"] = data["offers_tytan"].with_columns(
    pl.col("CITY").str.to_uppercase()
)

In [33]:
data["offers_tytan"] = data["offers_tytan"].with_columns(
    pl.col("DATE_ADDED").dt.strftime("%A").alias("DAY_NAME_EN")
)

In [34]:
geo_df = pl.DataFrame([
    {"CITY": k, "LAT": v["lat"], "LON": v["lon"]} 
    for k, v in CITIES_GEO.items()
])

data["offers_tytan"] = data["offers_tytan"].join(geo_df, on="CITY", how="left")

In [35]:
data["offers_tytan"].filter(pl.col("LAT").is_null())["CITY"].unique().to_list()

[]

# GRALCZYK

In [36]:
data["offers_gralczyk"] = data["offers_gralczyk"].rename({"FIRST_ADDED":"DATE_ADDED"})

In [37]:
data["offers_gralczyk"] = data["offers_gralczyk"].with_columns(
    pl.col(["LAST_UPDATED", "DATE_ADDED"]).str.to_date(format="%Y-%m-%d")
            )

In [38]:
data["offers_gralczyk"] = data["offers_gralczyk"].rename({"Cena":"PRICE"})
data["offers_gralczyk"] = data["offers_gralczyk"].rename({"Cena za m2":"PRICE_M2"})

In [39]:
data["offers_gralczyk"] = data["offers_gralczyk"].rename({"Powierzchnia":"AREA_M2"})

In [40]:
data["offers_gralczyk"] = data["offers_gralczyk"].with_columns(
    pl.col("AREA_M2")
    .str.replace("  m2", "")
    .str.replace(" ", "")
    .str.replace(",", ".")       
    .cast(pl.Float64)
)

In [41]:
data["offers_gralczyk"]

shape: (32, 26)
┌───────────────────┬────────────┬─────────┬──────────┬───┬──────────┬───────────────────┬───────────────┬─────────────┐
│ ID                ┆ DATE_ADDED ┆ PRICE   ┆ PRICE_M2 ┆ … ┆ Woda     ┆ Wygląd działki    ┆ Wysokość min. ┆ Łącze       │
│ ---               ┆ ---        ┆ ---     ┆ ---      ┆   ┆ ---      ┆ ---               ┆ ---           ┆ internetowe │
│ str               ┆ date       ┆ str     ┆ str      ┆   ┆ str      ┆ str               ┆ str           ┆ ---         │
│                   ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆ str         │
╞═══════════════════╪════════════╪═════════╪══════════╪═══╪══════════╪═══════════════════╪═══════════════╪═════════════╡
│ lomza-nowogrodzka ┆ 2025-11-22 ┆ 1650000 ┆ 201.88   ┆ … ┆ miejska  ┆ teren płaski,     ┆ 10            ┆ światłowód  │
│ -dzialka-inwestyc ┆            ┆         ┆          ┆   ┆          ┆ pusta             ┆               ┆             │
│ yjna-z-ogromnym-p ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ otencjalem        ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ lomza-bohdana-win ┆ 2025-11-22 ┆ 265000  ┆ 350.99   ┆ … ┆ miejska  ┆ teren płaski,     ┆ null          ┆ brak        │
│ iarskiego-dzialka ┆            ┆         ┆          ┆   ┆          ┆ pusta             ┆               ┆             │
│ -pod-budowe-twoje ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ go-wymarzonego-do ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ mu                ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ lomza-kalinowa-wy ┆ 2025-11-22 ┆ 465000  ┆ 178.98   ┆ … ┆ miejska  ┆ teren płaski,     ┆ 10            ┆ światłowód  │
│ jatkowa-dzialka-b ┆            ┆         ┆          ┆   ┆          ┆ pusta, linia      ┆               ┆             │
│ udowlana-w-lomzy- ┆            ┆         ┆          ┆   ┆          ┆ brzegowa          ┆               ┆             │
│ ul-kalinowa-os-pi ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ aski              ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ lomza-laczna-dzia ┆ 2025-11-22 ┆ 165000  ┆ 471.43   ┆ … ┆ miejska  ┆ zabudowana        ┆ 2             ┆ światłowód  │
│ lka-budowlana-w-b ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ ardzo-atrakcyjnej ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ -lokalizacji      ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ lomza-krolowej-bo ┆ 2025-11-22 ┆ 299000  ┆ 327.49   ┆ … ┆ miejska  ┆ teren             ┆ 2             ┆ brak        │
│ ny-dzialka-budowl ┆            ┆         ┆          ┆   ┆          ┆ zróżnicowany,     ┆               ┆             │
│ ana-w-swietnej-lo ┆            ┆         ┆          ┆   ┆          ┆ pusta             ┆               ┆             │
│ kalizacji         ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ …                 ┆ …          ┆ …       ┆ …        ┆ … ┆ …        ┆ …                 ┆ …             ┆ …           │
│ szczepankowo-dzia ┆ 2026-03-11 ┆ 80343   ┆ 79       ┆ … ┆ studnia  ┆ pusta             ┆ 6             ┆ brak        │
│ lki-w-atrakcyjnyc ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ h-cenach-blisko-n ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ atury             ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ motyka-malownicze ┆ 2026-03-12 ┆ 90000   ┆ 79.51    ┆ … ┆ w drodze ┆ teren płaski,     ┆ null          ┆ inne        │
│ -dzialki-w-sasied ┆            ┆         ┆          ┆   ┆          ┆ pusta             ┆               ┆             │
│ ztwie-lasu-motyka ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ gielczyn-jalowcow ┆ 2026-03-14 ┆ 275000  ┆ 118.23   ┆ … ┆ miejska  ┆ teren płaski,     ┆ 11            ┆ światłowód  │
│ a-dzialka-budowla ┆            ┆         ┆          ┆   ┆          ┆ pusta, zabudowana ┆               ┆             │
│ na-w-gielczynie-r ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ ozpoczeta-budowa- ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ pnb-media         ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ gielczyn-jalowcow ┆ 2026-03-14 ┆ 150000  ┆ 127.33   ┆ … ┆ miejska  ┆ teren płaski,     ┆ 11            ┆ światłowód  │
│ a-dzialki-budowla ┆            ┆         ┆          ┆   ┆          ┆ pusta, zabudowana ┆               ┆             │
│ ne-w-gielczynie-b ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ lisko-lomzy-media ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ -projekt-domu     ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ zosin-chabrowa-ma ┆ 2026-03-14 ┆ 210000  ┆ 140      ┆ … ┆ do 100m  ┆ teren płaski,     ┆ 2             ┆ brak        │
│ lownicze-dzialki- ┆            ┆         ┆          ┆   ┆          ┆ pusta             ┆               ┆             │
│ w-zosinie-blisko- ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
│ lomzy             ┆            ┆         ┆          ┆   ┆          ┆                   ┆               ┆             │
└───────────────────┴────────────┴─────────┴──────────┴───┴──────────┴───────────────────┴───────────────┴─────────────┘

In [42]:
data["offers_gralczyk"] = data["offers_gralczyk"].with_columns(
    pl.col("ID")
    .str.replace_all("dzialka", "")
    .str.replace_all("-", " ")      
    .str.strip_chars()              
    .str.to_uppercase()             
    .alias("CITY")                  
)

In [43]:
data["offers_gralczyk"]

shape: (32, 27)
┌────────────────┬────────────┬─────────┬──────────┬───┬───────────────┬───────────────┬───────────────┬───────────────┐
│ ID             ┆ DATE_ADDED ┆ PRICE   ┆ PRICE_M2 ┆ … ┆ Wygląd        ┆ Wysokość min. ┆ Łącze         ┆ CITY          │
│ ---            ┆ ---        ┆ ---     ┆ ---      ┆   ┆ działki       ┆ ---           ┆ internetowe   ┆ ---           │
│ str            ┆ date       ┆ str     ┆ str      ┆   ┆ ---           ┆ str           ┆ ---           ┆ str           │
│                ┆            ┆         ┆          ┆   ┆ str           ┆               ┆ str           ┆               │
╞════════════════╪════════════╪═════════╪══════════╪═══╪═══════════════╪═══════════════╪═══════════════╪═══════════════╡
│ lomza-nowogrod ┆ 2025-11-22 ┆ 1650000 ┆ 201.88   ┆ … ┆ teren płaski, ┆ 10            ┆ światłowód    ┆ LOMZA         │
│ zka-dzialka-in ┆            ┆         ┆          ┆   ┆ pusta         ┆               ┆               ┆ NOWOGRODZKA   │
│ westycyjna-z-o ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ INWESTYCYJNA  │
│ gromnym-potenc ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ Z OGROMNYM    │
│ jalem          ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ POTENCJALEM   │
│ lomza-bohdana- ┆ 2025-11-22 ┆ 265000  ┆ 350.99   ┆ … ┆ teren płaski, ┆ null          ┆ brak          ┆ LOMZA BOHDANA │
│ winiarskiego-d ┆            ┆         ┆          ┆   ┆ pusta         ┆               ┆               ┆ WINIARSKIEGO  │
│ zialka-pod-bud ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ POD BUDOWE    │
│ owe-twojego-wy ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ TWOJEGO       │
│ marzonego-domu ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ WYMARZONEGO   │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ DOMU          │
│ lomza-kalinowa ┆ 2025-11-22 ┆ 465000  ┆ 178.98   ┆ … ┆ teren płaski, ┆ 10            ┆ światłowód    ┆ LOMZA         │
│ -wyjatkowa-dzi ┆            ┆         ┆          ┆   ┆ pusta, linia  ┆               ┆               ┆ KALINOWA      │
│ alka-budowlana ┆            ┆         ┆          ┆   ┆ brzegowa      ┆               ┆               ┆ WYJATKOWA     │
│ -w-lomzy-ul-ka ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BUDOWLANA W   │
│ linowa-os-pias ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ LOMZY UL      │
│ ki             ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ KALINOWA OS   │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ PIASKI        │
│ lomza-laczna-d ┆ 2025-11-22 ┆ 165000  ┆ 471.43   ┆ … ┆ zabudowana    ┆ 2             ┆ światłowód    ┆ LOMZA LACZNA  │
│ zialka-budowla ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BUDOWLANA W   │
│ na-w-bardzo-at ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BARDZO        │
│ rakcyjnej-loka ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ ATRAKCYJNEJ   │
│ lizacji        ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ LOKALIZACJI   │
│ lomza-krolowej ┆ 2025-11-22 ┆ 299000  ┆ 327.49   ┆ … ┆ teren         ┆ 2             ┆ brak          ┆ LOMZA         │
│ -bony-dzialka- ┆            ┆         ┆          ┆   ┆ zróżnicowany, ┆               ┆               ┆ KROLOWEJ BONY │
│ budowlana-w-sw ┆            ┆         ┆          ┆   ┆ pusta         ┆               ┆               ┆ BUDOWLANA W   │
│ ietnej-lokaliz ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ SWIETNEJ      │
│ acji           ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ LOKALIZACJI   │
│ …              ┆ …          ┆ …       ┆ …        ┆ … ┆ …             ┆ …             ┆ …             ┆ …             │
│ szczepankowo-d ┆ 2026-03-11 ┆ 80343   ┆ 79       ┆ … ┆ pusta         ┆ 6             ┆ brak          ┆ SZCZEPANKOWO  │
│ zialki-w-atrak ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ DZIALKI W     │
│ cyjnych-cenach ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ ATRAKCYJNYCH  │
│ -blisko-natury ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ CENACH BLISKO │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ NATURY        │
│ motyka-malowni ┆ 2026-03-12 ┆ 90000   ┆ 79.51    ┆ … ┆ teren płaski, ┆ null          ┆ inne          ┆ MOTYKA        │
│ cze-dzialki-w- ┆            ┆         ┆          ┆   ┆ pusta         ┆               ┆               ┆ MALOWNICZE    │
│ sasiedztwie-la ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ DZIALKI W     │
│ su-motyka      ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ SASIEDZTWIE   │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ LASU MOTYKA   │
│ gielczyn-jalow ┆ 2026-03-14 ┆ 275000  ┆ 118.23   ┆ … ┆ teren płaski, ┆ 11            ┆ światłowód    ┆ GIELCZYN      │
│ cowa-dzialka-b ┆            ┆         ┆          ┆   ┆ pusta,        ┆               ┆               ┆ JALOWCOWA     │
│ udowlana-w-gie ┆            ┆         ┆          ┆   ┆ zabudowana    ┆               ┆               ┆ BUDOWLANA W   │
│ lczynie-rozpoc ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ GIELCZYNIE    │
│ zeta-budowa-pn ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ ROZPOCZETA    │
│ b-media        ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BUDOWA PNB    │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ MEDIA         │
│ gielczyn-jalow ┆ 2026-03-14 ┆ 150000  ┆ 127.33   ┆ … ┆ teren płaski, ┆ 11            ┆ światłowód    ┆ GIELCZYN      │
│ cowa-dzialki-b ┆            ┆         ┆          ┆   ┆ pusta,        ┆               ┆               ┆ JALOWCOWA     │
│ udowlane-w-gie ┆            ┆         ┆          ┆   ┆ zabudowana    ┆               ┆               ┆ DZIALKI       │
│ lczynie-blisko ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BUDOWLANE W   │
│ -lomzy-media-p ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ GIELCZYNIE    │
│ rojekt-domu    ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BLISKO LOMZY  │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ MEDIA PROJEKT │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ DOMU          │
│ zosin-chabrowa ┆ 2026-03-14 ┆ 210000  ┆ 140      ┆ … ┆ teren płaski, ┆ 2             ┆ brak          ┆ ZOSIN         │
│ -malownicze-dz ┆            ┆         ┆          ┆   ┆ pusta         ┆               ┆               ┆ CHABROWA      │
│ ialki-w-zosini ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ MALOWNICZE    │
│ e-blisko-lomzy ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ DZIALKI W     │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ ZOSINIE       │
│                ┆            ┆         ┆          ┆   ┆               ┆               ┆               ┆ BLISKO LOMZY  │
└────────────────┴────────────┴─────────┴──────────┴───┴───────────────┴───────────────┴───────────────┴───────────────┘

In [44]:
data["offers_gralczyk"] = data["offers_gralczyk"].with_columns(
    pl.col("CITY")
    .str.to_uppercase()
    .str.replace_all("Ł", "L")
    .str.replace_all("Ó", "O")
    .str.replace_all("Ś", "S")
    .str.replace_all("Ż", "Z")
    .str.replace_all("Ź", "Z")
    .str.replace_all("Ć", "C")
    .str.replace_all("Ń", "N")
    .str.replace_all("Ą", "A")
    .str.replace_all("Ę", "E")
    .alias("SEARCH_CITY")
)

condition = pl.when(False).then(None)

for original_city in CITIES_GEO.keys():
    simple_city = simplify_text(original_city) 
    
    condition = condition.when(
        pl.col("SEARCH_CITY").str.contains(simple_city)
    ).then(pl.lit(original_city)) 

data["offers_gralczyk"] = data["offers_gralczyk"].with_columns(
    condition.alias("CLEAN_CITY")
)

data["offers_gralczyk"] = data["offers_gralczyk"].drop("SEARCH_CITY")

In [45]:
data["offers_gralczyk"].filter(pl.col("CLEAN_CITY").is_null())["CITY"].unique().to_list()

[]

In [46]:
data["offers_gralczyk"] = data["offers_gralczyk"].drop( ["CITY"])
data["offers_gralczyk"] = data["offers_gralczyk"].rename({"CLEAN_CITY":"CITY"})

In [47]:
data["offers_gralczyk"] = data["offers_gralczyk"].join(geo_df, on="CITY", how="left")

In [48]:
data["offers_gralczyk"].head(2)

shape: (2, 29)
┌─────────────────────────────┬────────────┬─────────┬──────────┬───┬───────────────────┬──────────┬─────────┬─────────┐
│ ID                          ┆ DATE_ADDED ┆ PRICE   ┆ PRICE_M2 ┆ … ┆ Łącze internetowe ┆ CITY     ┆ LAT     ┆ LON     │
│ ---                         ┆ ---        ┆ ---     ┆ ---      ┆   ┆ ---               ┆ ---      ┆ ---     ┆ ---     │
│ str                         ┆ date       ┆ str     ┆ str      ┆   ┆ str               ┆ str      ┆ f64     ┆ f64     │
╞═════════════════════════════╪════════════╪═════════╪══════════╪═══╪═══════════════════╪══════════╪═════════╪═════════╡
│ lomza-nowogrodzka-dzialka-i ┆ 2025-11-22 ┆ 1650000 ┆ 201.88   ┆ … ┆ światłowód        ┆ NOWOGRÓD ┆ 53.2264 ┆ 21.8806 │
│ nwestycyjna-z-ogromnym-pote ┆            ┆         ┆          ┆   ┆                   ┆          ┆         ┆         │
│ ncjalem                     ┆            ┆         ┆          ┆   ┆                   ┆          ┆         ┆         │
│ lomza-bohdana-winiarskiego- ┆ 2025-11-22 ┆ 265000  ┆ 350.99   ┆ … ┆ brak              ┆ ŁOMŻA    ┆ 53.1781 ┆ 22.0592 │
│ dzialka-pod-budowe-twojego- ┆            ┆         ┆          ┆   ┆                   ┆          ┆         ┆         │
│ wymarzonego-domu            ┆            ┆         ┆          ┆   ┆                   ┆          ┆         ┆         │
└─────────────────────────────┴────────────┴─────────┴──────────┴───┴───────────────────┴──────────┴─────────┴─────────┘

# POLNOC

In [49]:
data["offers_polnoc"] = data["offers_polnoc"].rename({"FIRST_ADDED":"DATE_ADDED"})

In [50]:
data["offers_polnoc"] = data["offers_polnoc"].with_columns(
    pl.col(["LAST_UPDATED", "DATE_ADDED"]).str.to_date(format="%Y-%m-%d")
            )

In [51]:
data["offers_polnoc"] = data["offers_polnoc"].rename({"Cena":"PRICE"})
data["offers_polnoc"] = data["offers_polnoc"].rename({"Cena za m2":"PRICE_M2"})
data["offers_polnoc"] = data["offers_polnoc"].rename({"Powierzchnia działki":"AREA_M2"})

In [52]:
data["offers_polnoc"] = data["offers_polnoc"].filter(
    (pl.col("AREA_M2").is_not_null()) & 
    (pl.col("ID").str.contains("dzialka"))
)

In [53]:
data["offers_polnoc"]

shape: (45, 30)
┌──────────────────┬────────────┬──────────────┬──────────┬───┬────────────┬─────────────────┬─────────────────┬───────┐
│ ID               ┆ DATE_ADDED ┆ LAST_UPDATED ┆ PRICE    ┆ … ┆ Typ kuchni ┆ Tytuł           ┆ Ukształtowanie  ┆ Winda │
│ ---              ┆ ---        ┆ ---          ┆ ---      ┆   ┆ ---        ┆ ---             ┆ działki         ┆ ---   │
│ str              ┆ date       ┆ date         ┆ str      ┆   ┆ str        ┆ str             ┆ ---             ┆ str   │
│                  ┆            ┆              ┆          ┆   ┆            ┆                 ┆ str             ┆       │
╞══════════════════╪════════════╪══════════════╪══════════╪═══╪════════════╪═════════════════╪═════════════════╪═══════╡
│ dzialka-pupki    ┆ 2025-11-22 ┆ 2026-01-31   ┆ 94000.0  ┆ … ┆ null       ┆ Na sprzedaż     ┆ Płaska          ┆ null  │
│                  ┆            ┆              ┆          ┆   ┆            ┆ działki         ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ budowlane w     ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Pupkach,        ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ gm.Turośl       ┆                 ┆       │
│ dzialka-stare-ku ┆ 2025-11-22 ┆ 2025-12-02   ┆ 129000.0 ┆ … ┆ null       ┆ Działka         ┆ Płaska          ┆ null  │
│ piski-ul-wspolna ┆            ┆              ┆          ┆   ┆            ┆ budowlana z WZ  ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ w Starych       ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Kupiskach!      ┆                 ┆       │
│ dzialka-lomza-zd ┆ 2025-11-22 ┆ 2026-01-31   ┆ 249000.0 ┆ … ┆ null       ┆ Działka w Łomży ┆ Zróżnicowana    ┆ null  │
│ rojowa           ┆            ┆              ┆          ┆   ┆            ┆ na ul.          ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Zdrojowej!      ┆                 ┆       │
│ dzialka-lomza-wa ┆ 2025-11-22 ┆ 2026-01-31   ┆ 205000.0 ┆ … ┆ null       ┆ Malownicza      ┆ Płaska          ┆ null  │
│ ska              ┆            ┆              ┆          ┆   ┆            ┆ działka w Łomży ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ na ul. Wąskiej! ┆                 ┆       │
│ dzialka-lomza-gr ┆ 2025-11-22 ┆ 2026-01-31   ┆ 239000.0 ┆ … ┆ null       ┆ Przestronne     ┆ Płaska          ┆ null  │
│ abowa            ┆            ┆              ┆          ┆   ┆            ┆ działki w Łomży ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ na ul.          ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Grabowej!       ┆                 ┆       │
│ …                ┆ …          ┆ …            ┆ …        ┆ … ┆ …          ┆ …               ┆ …               ┆ …     │
│ dzialka-lomza-ul ┆ 2025-12-31 ┆ 2026-02-14   ┆ 370000.0 ┆ … ┆ null       ┆ Działka –       ┆ Płaska          ┆ null  │
│ -dzialkowa       ┆            ┆              ┆          ┆   ┆            ┆ Łomża, ul.      ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Działkowa       ┆                 ┆       │
│ dzialka-lomza-ul ┆ 2026-01-09 ┆ 2026-01-31   ┆ 370000.0 ┆ … ┆ null       ┆ Działka –       ┆ Płaska          ┆ null  │
│ -dzialkowa-2     ┆            ┆              ┆          ┆   ┆            ┆ Łomża, ul.      ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Działkowa       ┆                 ┆       │
│ dzialka-budy-cza ┆ 2026-01-09 ┆ 2026-01-31   ┆ 105000.0 ┆ … ┆ null       ┆ Atrakcyjna      ┆ Płaska          ┆ null  │
│ rnockie-2        ┆            ┆              ┆          ┆   ┆            ┆ działka w       ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Budach          ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Czarnockich!    ┆                 ┆       │
│ dzialka-lomza-dz ┆ 2026-01-09 ┆ 2026-01-31   ┆ 370000.0 ┆ … ┆ null       ┆ Działka –       ┆ Płaska          ┆ null  │
│ ialkowa          ┆            ┆              ┆          ┆   ┆            ┆ Łomża,          ┆                 ┆       │
│                  ┆            ┆              ┆          ┆   ┆            ┆ Działkowa       ┆                 ┆       │
│ dzialka-nowy-cyd ┆ 2026-01-27 ┆ 2026-02-19   ┆ 145000.0 ┆ … ┆ null       ┆ Działka – Nowy  ┆ Płaska          ┆ null  │
│ zyn              ┆            ┆              ┆          ┆   ┆            ┆ Cydzyn          ┆                 ┆       │
└──────────────────┴────────────┴──────────────┴──────────┴───┴────────────┴─────────────────┴─────────────────┴───────┘

In [54]:
data["offers_polnoc"] = data["offers_polnoc"].with_columns(
    pl.col("ID")
    .str.replace_all("dzialka", "")
    .str.replace_all("-", " ")      
    .str.strip_chars()              
    .str.to_uppercase()             
    .alias("CITY")                  
)

In [55]:
data["offers_polnoc"]

shape: (45, 31)
┌────────────────┬────────────┬──────────────┬──────────┬───┬────────────────┬────────────────┬───────┬────────────────┐
│ ID             ┆ DATE_ADDED ┆ LAST_UPDATED ┆ PRICE    ┆ … ┆ Tytuł          ┆ Ukształtowanie ┆ Winda ┆ CITY           │
│ ---            ┆ ---        ┆ ---          ┆ ---      ┆   ┆ ---            ┆ działki        ┆ ---   ┆ ---            │
│ str            ┆ date       ┆ date         ┆ str      ┆   ┆ str            ┆ ---            ┆ str   ┆ str            │
│                ┆            ┆              ┆          ┆   ┆                ┆ str            ┆       ┆                │
╞════════════════╪════════════╪══════════════╪══════════╪═══╪════════════════╪════════════════╪═══════╪════════════════╡
│ dzialka-pupki  ┆ 2025-11-22 ┆ 2026-01-31   ┆ 94000.0  ┆ … ┆ Na sprzedaż    ┆ Płaska         ┆ null  ┆ PUPKI          │
│                ┆            ┆              ┆          ┆   ┆ działki        ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ budowlane w    ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Pupkach,       ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ gm.Turośl      ┆                ┆       ┆                │
│ dzialka-stare- ┆ 2025-11-22 ┆ 2025-12-02   ┆ 129000.0 ┆ … ┆ Działka        ┆ Płaska         ┆ null  ┆ STARE KUPISKI  │
│ kupiski-ul-wsp ┆            ┆              ┆          ┆   ┆ budowlana z WZ ┆                ┆       ┆ UL WSPOLNA     │
│ olna           ┆            ┆              ┆          ┆   ┆ w Starych      ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Kupiskach!     ┆                ┆       ┆                │
│ dzialka-lomza- ┆ 2025-11-22 ┆ 2026-01-31   ┆ 249000.0 ┆ … ┆ Działka w      ┆ Zróżnicowana   ┆ null  ┆ LOMZA ZDROJOWA │
│ zdrojowa       ┆            ┆              ┆          ┆   ┆ Łomży na ul.   ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Zdrojowej!     ┆                ┆       ┆                │
│ dzialka-lomza- ┆ 2025-11-22 ┆ 2026-01-31   ┆ 205000.0 ┆ … ┆ Malownicza     ┆ Płaska         ┆ null  ┆ LOMZA WASKA    │
│ waska          ┆            ┆              ┆          ┆   ┆ działka w      ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Łomży na ul.   ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Wąskiej!       ┆                ┆       ┆                │
│ dzialka-lomza- ┆ 2025-11-22 ┆ 2026-01-31   ┆ 239000.0 ┆ … ┆ Przestronne    ┆ Płaska         ┆ null  ┆ LOMZA GRABOWA  │
│ grabowa        ┆            ┆              ┆          ┆   ┆ działki w      ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Łomży na ul.   ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Grabowej!      ┆                ┆       ┆                │
│ …              ┆ …          ┆ …            ┆ …        ┆ … ┆ …              ┆ …              ┆ …     ┆ …              │
│ dzialka-lomza- ┆ 2025-12-31 ┆ 2026-02-14   ┆ 370000.0 ┆ … ┆ Działka –      ┆ Płaska         ┆ null  ┆ LOMZA UL       │
│ ul-dzialkowa   ┆            ┆              ┆          ┆   ┆ Łomża, ul.     ┆                ┆       ┆ DZIALKOWA      │
│                ┆            ┆              ┆          ┆   ┆ Działkowa      ┆                ┆       ┆                │
│ dzialka-lomza- ┆ 2026-01-09 ┆ 2026-01-31   ┆ 370000.0 ┆ … ┆ Działka –      ┆ Płaska         ┆ null  ┆ LOMZA UL       │
│ ul-dzialkowa-2 ┆            ┆              ┆          ┆   ┆ Łomża, ul.     ┆                ┆       ┆ DZIALKOWA 2    │
│                ┆            ┆              ┆          ┆   ┆ Działkowa      ┆                ┆       ┆                │
│ dzialka-budy-c ┆ 2026-01-09 ┆ 2026-01-31   ┆ 105000.0 ┆ … ┆ Atrakcyjna     ┆ Płaska         ┆ null  ┆ BUDY           │
│ zarnockie-2    ┆            ┆              ┆          ┆   ┆ działka w      ┆                ┆       ┆ CZARNOCKIE 2   │
│                ┆            ┆              ┆          ┆   ┆ Budach         ┆                ┆       ┆                │
│                ┆            ┆              ┆          ┆   ┆ Czarnockich!   ┆                ┆       ┆                │
│ dzialka-lomza- ┆ 2026-01-09 ┆ 2026-01-31   ┆ 370000.0 ┆ … ┆ Działka –      ┆ Płaska         ┆ null  ┆ LOMZA          │
│ dzialkowa      ┆            ┆              ┆          ┆   ┆ Łomża,         ┆                ┆       ┆ DZIALKOWA      │
│                ┆            ┆              ┆          ┆   ┆ Działkowa      ┆                ┆       ┆                │
│ dzialka-nowy-c ┆ 2026-01-27 ┆ 2026-02-19   ┆ 145000.0 ┆ … ┆ Działka – Nowy ┆ Płaska         ┆ null  ┆ NOWY CYDZYN    │
│ ydzyn          ┆            ┆              ┆          ┆   ┆ Cydzyn         ┆                ┆       ┆                │
└────────────────┴────────────┴──────────────┴──────────┴───┴────────────────┴────────────────┴───────┴────────────────┘

In [56]:
data["offers_polnoc"] = data["offers_polnoc"].with_columns(
    pl.col(["AREA_M2", "PRICE_M2", "PRICE"]).cast(pl.Float64)
)

In [57]:
data["offers_polnoc"] = data["offers_polnoc"].with_columns(
    pl.col("CITY")
    .str.to_uppercase()
    .str.replace_all("Ł", "L")
    .str.replace_all("Ó", "O")
    .str.replace_all("Ś", "S")
    .str.replace_all("Ż", "Z")
    .str.replace_all("Ź", "Z")
    .str.replace_all("Ć", "C")
    .str.replace_all("Ń", "N")
    .str.replace_all("Ą", "A")
    .str.replace_all("Ę", "E")
    .alias("SEARCH_CITY")
)

condition = pl.when(False).then(None)

for original_city in CITIES_GEO.keys():
    simple_city = simplify_text(original_city) 
    
    condition = condition.when(
        pl.col("SEARCH_CITY").str.contains(simple_city)
    ).then(pl.lit(original_city)) 

data["offers_polnoc"] = data["offers_polnoc"].with_columns(
    condition.alias("CLEAN_CITY")
)

data["offers_polnoc"] = data["offers_polnoc"].drop("SEARCH_CITY")

In [58]:
data["offers_polnoc"].filter(pl.col("CLEAN_CITY").is_null())["CITY"].unique().to_list()

[]

In [59]:
data["offers_polnoc"] = data["offers_polnoc"].drop( ["CITY"])
data["offers_polnoc"] = data["offers_polnoc"].rename({"CLEAN_CITY":"CITY"})
data["offers_polnoc"] = data["offers_polnoc"].join(geo_df, on="CITY", how="left")

In [60]:
data["offers_polnoc"]

shape: (45, 33)
┌─────────────────────────────┬────────────┬──────────────┬──────────┬───┬───────┬─────────────────┬─────────┬─────────┐
│ ID                          ┆ DATE_ADDED ┆ LAST_UPDATED ┆ PRICE    ┆ … ┆ Winda ┆ CITY            ┆ LAT     ┆ LON     │
│ ---                         ┆ ---        ┆ ---          ┆ ---      ┆   ┆ ---   ┆ ---             ┆ ---     ┆ ---     │
│ str                         ┆ date       ┆ date         ┆ f64      ┆   ┆ str   ┆ str             ┆ f64     ┆ f64     │
╞═════════════════════════════╪════════════╪══════════════╪══════════╪═══╪═══════╪═════════════════╪═════════╪═════════╡
│ dzialka-pupki               ┆ 2025-11-22 ┆ 2026-01-31   ┆ 94000.0  ┆ … ┆ null  ┆ PUPKI           ┆ 53.2258 ┆ 21.8497 │
│ dzialka-stare-kupiski-ul-ws ┆ 2025-11-22 ┆ 2025-12-02   ┆ 129000.0 ┆ … ┆ null  ┆ STARE KUPISKI   ┆ 53.1972 ┆ 21.9964 │
│ polna                       ┆            ┆              ┆          ┆   ┆       ┆                 ┆         ┆         │
│ dzialka-lomza-zdrojowa      ┆ 2025-11-22 ┆ 2026-01-31   ┆ 249000.0 ┆ … ┆ null  ┆ ŁOMŻA           ┆ 53.1781 ┆ 22.0592 │
│ dzialka-lomza-waska         ┆ 2025-11-22 ┆ 2026-01-31   ┆ 205000.0 ┆ … ┆ null  ┆ ŁOMŻA           ┆ 53.1781 ┆ 22.0592 │
│ dzialka-lomza-grabowa       ┆ 2025-11-22 ┆ 2026-01-31   ┆ 239000.0 ┆ … ┆ null  ┆ ŁOMŻA           ┆ 53.1781 ┆ 22.0592 │
│ …                           ┆ …          ┆ …            ┆ …        ┆ … ┆ …     ┆ …               ┆ …       ┆ …       │
│ dzialka-lomza-ul-dzialkowa  ┆ 2025-12-31 ┆ 2026-02-14   ┆ 370000.0 ┆ … ┆ null  ┆ ŁOMŻA           ┆ 53.1781 ┆ 22.0592 │
│ dzialka-lomza-ul-dzialkowa- ┆ 2026-01-09 ┆ 2026-01-31   ┆ 370000.0 ┆ … ┆ null  ┆ ŁOMŻA           ┆ 53.1781 ┆ 22.0592 │
│ 2                           ┆            ┆              ┆          ┆   ┆       ┆                 ┆         ┆         │
│ dzialka-budy-czarnockie-2   ┆ 2026-01-09 ┆ 2026-01-31   ┆ 105000.0 ┆ … ┆ null  ┆ BUDY CZARNOCKIE ┆ 53.2167 ┆ 22.15   │
│ dzialka-lomza-dzialkowa     ┆ 2026-01-09 ┆ 2026-01-31   ┆ 370000.0 ┆ … ┆ null  ┆ ŁOMŻA           ┆ 53.1781 ┆ 22.0592 │
│ dzialka-nowy-cydzyn         ┆ 2026-01-27 ┆ 2026-02-19   ┆ 145000.0 ┆ … ┆ null  ┆ NOWY CYDZYN     ┆ 53.2753 ┆ 22.1764 │
└─────────────────────────────┴────────────┴──────────────┴──────────┴───┴───────┴─────────────────┴─────────┴─────────┘

# 4LOMZA

In [61]:
data["analyzed_offers"] = data["analyzed_offers"].filter((pl.col("ESTATE_TYPE").str.contains("DZIAŁKA BUDOWLANA"))&
                               (pl.col("OFFER_TYPE").str.contains("SPRZEDAZ")))

In [62]:
data["analyzed_offers"] = data["analyzed_offers"].unique(subset=["ID"])

In [63]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.col(["LAST_UPDATED", "DATE_ADDED"]).str.to_date(format="%Y-%m-%d")
            )

In [64]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.col([ "ANNOUNCE_DATE"]).str.to_date(format="%Y-%m-%d")
            )

In [65]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.col("AREA_M2")
    .str.replace(" m2", "")
    .str.replace(",", ".")
    .cast(pl.Float64, strict=False)  
)

In [66]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.col("PRICE")
    .str.replace(" m2", "")
    .str.replace(",", ".")
    .cast(pl.Float64, strict=False)  
)

In [67]:
data["analyzed_offers"]

shape: (192, 12)
┌────────────────┬────────────┬──────────────┬───────────────┬───┬────────────────┬──────────┬─────────┬───────────────┐
│ ID             ┆ DATE_ADDED ┆ LAST_UPDATED ┆ ANNOUNCE_DATE ┆ … ┆ ESTATE_TYPE    ┆ PRICE    ┆ AREA_M2 ┆ LOCATION      │
│ ---            ┆ ---        ┆ ---          ┆ ---           ┆   ┆ ---            ┆ ---      ┆ ---     ┆ ---           │
│ str            ┆ date       ┆ date         ┆ date          ┆   ┆ str            ┆ f64      ┆ f64     ┆ str           │
╞════════════════╪════════════╪══════════════╪═══════════════╪═══╪════════════════╪══════════╪═════════╪═══════════════╡
│ sprzedam       ┆ 2025-12-28 ┆ 2026-01-03   ┆ 2025-12-27    ┆ … ┆ DZIAŁKA        ┆ null     ┆ 701.0   ┆ ŁOMŻA         │
│ działkę        ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ budowlaną      ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ w_2025-12-27   ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2026-01-20 ┆ 2026-01-26   ┆ 2026-01-19    ┆ … ┆ DZIAŁKA        ┆ null     ┆ null    ┆ KONARSKA      │
│ działkę        ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ budowlaną      ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ 10_2026-01-19  ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2026-02-20 ┆ 2026-02-23   ┆ 2026-02-20    ┆ … ┆ DZIAŁKA        ┆ 115000.0 ┆ 1275.0  ┆ NOWOGRÓD      │
│ działkę z bezt ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ erminowymi_202 ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ 6-02-20        ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2025-11-29 ┆ 2025-12-04   ┆ 2025-11-28    ┆ … ┆ DZIAŁKA        ┆ null     ┆ null    ┆ LOMZA         │
│ dzialke 8      ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ ary_2025-11-28 ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2025-12-01 ┆ 2025-12-06   ┆ 2025-11-30    ┆ … ┆ DZIAŁKA        ┆ 1.6e6    ┆ 1364.0  ┆ NOWOGRÓD      │
│ działkę        ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ budowlaną      ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ nr_2025-11-30  ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ …              ┆ …          ┆ …            ┆ …             ┆ … ┆ …              ┆ …        ┆ …       ┆ …             │
│ na sprzedaż    ┆ 2026-02-06 ┆ 2026-02-12   ┆ 2026-02-05    ┆ … ┆ DZIAŁKA        ┆ 110.0    ┆ 1054.0  ┆ NOWOGRÓD      │
│ działka budowl ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ ana_2026-02-05 ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2026-02-18 ┆ 2026-02-18   ┆ 2026-02-17    ┆ … ┆ DZIAŁKA        ┆ null     ┆ null    ┆ NOWOGRÓD UL   │
│ działkę        ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆ JANA PAWŁA LL │
│ budowlaną      ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ w_2026-02-17   ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ na sprzedaż    ┆ 2026-02-06 ┆ 2026-02-12   ┆ 2026-02-05    ┆ … ┆ DZIAŁKA        ┆ 0.0      ┆ 505.0   ┆ ŁOMŻA         │
│ atrakcyjna dzi ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆               │
│ ałka_2026-02-0 ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ 5              ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2026-01-08 ┆ 2026-01-14   ┆ 2026-01-07    ┆ … ┆ DZIAŁKA        ┆ null     ┆ null    ┆ BUDY          │
│ działkę        ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆ KRANOCKIE     │
│ budowlaną ok20 ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ ary_2026-01-07 ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ sprzedam       ┆ 2025-11-24 ┆ 2025-11-29   ┆ 2025-11-23    ┆ … ┆ DZIAŁKA        ┆ 0.0      ┆ 0.0     ┆ ZAWADY UL     │
│ działkę        ┆            ┆              ┆               ┆   ┆ BUDOWLANA      ┆          ┆         ┆ KONARSKA      │
│ budowlaną      ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
│ w_2025-11-23   ┆            ┆              ┆               ┆   ┆                ┆          ┆         ┆               │
└────────────────┴────────────┴──────────────┴───────────────┴───┴────────────────┴──────────┴─────────┴───────────────┘

In [68]:
stats = data["analyzed_offers"].select([
    pl.col("AREA_M2").quantile(0.25).alias("q1"),
    pl.col("AREA_M2").quantile(0.75).alias("q3")
])

q1 = stats[0, "q1"]
q3 = stats[0, "q3"]
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print(f"Statystyczne granice dla AREA_M2: {lower_bound:.2f} - {upper_bound:.2f}")

outliery_statystyczne = data["analyzed_offers"].filter(
    (pl.col("AREA_M2") < lower_bound) | (pl.col("AREA_M2") > upper_bound)
)

Statystyczne granice dla AREA_M2: -350.00 - 2450.00

In [69]:
corrected_outliers = outliery_statystyczne.with_columns(
    pl.when(
        (pl.col("TEXT").str.contains(f"(?i)ar")) | 
        (pl.col("TEXT").str.contains(f"(?i)ara"))   
    )
    .then(pl.col("AREA_M2") / 10)  
    .otherwise(pl.col("AREA_M2"))
    .alias("AREA_M2_CORRECTED")
).select(["ID", "AREA_M2_CORRECTED"])

In [70]:
data["analyzed_offers"] = data["analyzed_offers"].join(
    corrected_outliers, on="ID", how="left"
)

data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.col("AREA_M2_CORRECTED").fill_null(pl.col("AREA_M2")).alias("AREA_M2")
).drop("AREA_M2_CORRECTED")

In [71]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    (pl.col("PRICE") / pl.col("AREA_M2")).round(2).alias("PRICE_M2")
)

In [72]:
data["analyzed_offers"] = data["analyzed_offers"].rename({"LOCATION":"CITY"})

In [73]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.col("CITY")
    .str.to_uppercase()
    .str.replace_all("Ł", "L")
    .str.replace_all("Ó", "O")
    .str.replace_all("Ś", "S")
    .str.replace_all("Ż", "Z")
    .str.replace_all("Ź", "Z")
    .str.replace_all("Ć", "C")
    .str.replace_all("Ń", "N")
    .str.replace_all("Ą", "A")
    .str.replace_all("Ę", "E")
    .alias("SEARCH_CITY")
)

condition = pl.when(False).then(None)

for original_city in CITIES_GEO.keys():
    simple_city = simplify_text(original_city) 
    
    condition = condition.when(
        pl.col("SEARCH_CITY").str.contains(simple_city)
    ).then(pl.lit(original_city)) 

data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    condition.alias("CLEAN_CITY")
)

data["analyzed_offers"] = data["analyzed_offers"].drop("SEARCH_CITY")

In [74]:
data["analyzed_offers"].filter(pl.col("CLEAN_CITY").is_null())["CITY"].unique().to_list()

['POZNAŃSKA',
 'WALKOWA',
 'KONARSKA',
 'ELBLĄSKA',
 '12KM OD ŁOMŻY',
 '8 KM OD ŁOMŻY',
 'BRAK',
 'UL SŁONECZNA',
 'KRUCZA',
 'UL.DMOWSKIEGO',
 'MIASTKÓW']

In [75]:
data["analyzed_offers"] = data["analyzed_offers"].with_columns(
    pl.when(pl.col("CITY").str.to_uppercase() == "BRAK")
    .then(None) 
    .when(pl.col("CLEAN_CITY").is_null()) 
    .then(pl.lit("ŁOMŻA")) 
    .otherwise(pl.col("CLEAN_CITY")) 
    .alias("CLEAN_CITY")
)

In [76]:
data["analyzed_offers"] = data["analyzed_offers"].drop( ["CITY"])
data["analyzed_offers"] = data["analyzed_offers"].rename({"CLEAN_CITY":"CITY"})
data["analyzed_offers"] = data["analyzed_offers"].join(geo_df, on="CITY", how="left")

In [77]:
data.keys()

dict_keys(['offers', 'offers_tytan', 'offers_gralczyk', 'offers_polnoc', 'analyzed_offers'])

# Concating all datasets

In [78]:
for key in data.keys():
    print (key, data[key].columns)

offers ['ID', 'TEXT', 'LINK', 'VALUE', 'CURRENCY', 'NEGOTIABLE', 'AREA_M2', 'PRICE_M2', 'CITY', 'DATE_ORIG', 'LAST_UPDATED', 'DATE_ADDED', 'LAT', 'LON', 'DAY_NAME_EN']
offers_tytan ['ID', 'CITY', 'NAME', 'AREA_M2', 'PRICE', 'PRICE_M2', 'LINK', 'LAST_UPDATED', 'DATE_ADDED', 'DAY_NAME_EN', 'LAT', 'LON']
offers_gralczyk ['ID', 'DATE_ADDED', 'PRICE', 'PRICE_M2', 'Długość', 'Forma własności', 'Gaz', 'Kanalizacja', 'LAST_UPDATED', 'LINK', 'Liczba linii tel.', 'Numer oferty', 'AREA_M2', 'Powierzchnia zabudowy', 'Przeznaczenie', 'Prąd', 'Szerokość', 'Sąsiedztwo', 'Typ drogi', 'Typ działki', 'Typ ogrodzenia', 'Typ transakcji', 'Woda', 'Wygląd działki', 'Wysokość min.', 'Łącze internetowe', 'CITY', 'LAT', 'LON']
offers_polnoc ['ID', 'DATE_ADDED', 'LAST_UPDATED', 'PRICE', 'PRICE_M2', 'Ciepła woda', 'Długość działki (mb.)', 'Garaż/Miejsca parkingowe', 'Id oferty', 'Kształt działki', 'LINK', 'Liczba pięter', 'Liczba pokoi', 'Ogrodzenie', 'Piętro', 'Plan miejscowy', 'Powierzchnia', 'AREA_M2', 'Powierzchnia użytkowa', 'Przeznaczenie działki', 'Rodzaj budynku', 'Rok budowy', 'Rynek', 'Stan budynku', 'Szerokość działki (mb.)', 'Typ domu', 'Typ kuchni', 'Tytuł', 'Ukształtowanie działki', 'Winda', 'CITY', 'LAT', 'LON']
analyzed_offers ['ID', 'DATE_ADDED', 'LAST_UPDATED', 'ANNOUNCE_DATE', 'TEXT', 'ANALYSIS_RESULT', 'RAW_ARGS', 'OFFER_TYPE', 'ESTATE_TYPE', 'PRICE', 'AREA_M2', 'PRICE_M2', 'CITY', 'LAT', 'LON']

In [80]:
target_cols = ["ID", "DATE_ADDED", "LAST_UPDATED", "AREA_M2", "PRICE_M2", "CITY", "LAT", "LON", "PRICE"]

In [82]:
processed_dfs = []

for key, df in data.items():
    temp_df = df.rename({"VALUE": "PRICE"}) if "VALUE" in df.columns else df
    temp_df = temp_df.select(target_cols).with_columns([
        pl.col("ID").cast(pl.String),        
        pl.col("PRICE").cast(pl.Float64),  
        pl.col("AREA_M2").cast(pl.Float64),
        pl.col("PRICE_M2").cast(pl.Float64),
        pl.col("LAT").cast(pl.Float64),
        pl.col("LON").cast(pl.Float64),
        pl.lit(key).alias("SOURCE")
    ])
    processed_dfs.append(temp_df)

data["Offers_all"] = pl.concat(processed_dfs)

In [97]:
data["Offers_all"] = data["Offers_all"].with_columns([
    pl.when(pl.col("PRICE") < 15_000)
    .then(None)
    .otherwise(pl.col("PRICE"))
    .alias("PRICE"),
]).with_columns([
    pl.when(pl.col("PRICE").is_null())
    .then(None)
    .otherwise(pl.col("PRICE_M2"))
    .alias("PRICE_M2")
])

In [104]:
data["Offers_all"]

shape: (636, 10)
┌───────────────────────────┬────────────┬──────────────┬─────────┬───┬─────────┬─────────┬──────────┬─────────────────┐
│ ID                        ┆ DATE_ADDED ┆ LAST_UPDATED ┆ AREA_M2 ┆ … ┆ LAT     ┆ LON     ┆ PRICE    ┆ SOURCE          │
│ ---                       ┆ ---        ┆ ---          ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---      ┆ ---             │
│ str                       ┆ date       ┆ date         ┆ f64     ┆   ┆ f64     ┆ f64     ┆ f64      ┆ str             │
╞═══════════════════════════╪════════════╪══════════════╪═════════╪═══╪═════════╪═════════╪══════════╪═════════════════╡
│ Łomża_2134_99000          ┆ 2025-11-10 ┆ 2025-11-11   ┆ 2134.0  ┆ … ┆ 53.1781 ┆ 22.0592 ┆ 99000.0  ┆ offers          │
│ Zawady_1000_130000        ┆ 2026-02-11 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ 53.1539 ┆ 22.6653 ┆ 130000.0 ┆ offers          │
│ Elżbiecin_12200_1490000   ┆ 2026-02-10 ┆ 2025-11-11   ┆ 12200.0 ┆ … ┆ 53.1672 ┆ 22.1231 ┆ 1.49e6   ┆ offers          │
│ Jurki_3000_67500          ┆ 2025-11-06 ┆ 2025-11-11   ┆ 3000.0  ┆ … ┆ 53.3983 ┆ 22.1114 ┆ 67500.0  ┆ offers          │
│ Łomża_1000_129500         ┆ 2025-11-06 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ 53.1781 ┆ 22.0592 ┆ 129500.0 ┆ offers          │
│ …                         ┆ …          ┆ …            ┆ …       ┆ … ┆ …       ┆ …       ┆ …        ┆ …               │
│ na sprzedaż działka       ┆ 2026-02-06 ┆ 2026-02-12   ┆ 1054.0  ┆ … ┆ 53.2264 ┆ 21.8806 ┆ null     ┆ analyzed_offers │
│ budowlana_2026-02-05      ┆            ┆              ┆         ┆   ┆         ┆         ┆          ┆                 │
│ sprzedam działkę          ┆ 2026-02-18 ┆ 2026-02-18   ┆ null    ┆ … ┆ 53.2264 ┆ 21.8806 ┆ null     ┆ analyzed_offers │
│ budowlaną w_2026-02-17    ┆            ┆              ┆         ┆   ┆         ┆         ┆          ┆                 │
│ na sprzedaż atrakcyjna    ┆ 2026-02-06 ┆ 2026-02-12   ┆ 505.0   ┆ … ┆ 53.1781 ┆ 22.0592 ┆ null     ┆ analyzed_offers │
│ działka_2026-02-05        ┆            ┆              ┆         ┆   ┆         ┆         ┆          ┆                 │
│ sprzedam działkę          ┆ 2026-01-08 ┆ 2026-01-14   ┆ null    ┆ … ┆ 53.1958 ┆ 22.1486 ┆ null     ┆ analyzed_offers │
│ budowlaną                 ┆            ┆              ┆         ┆   ┆         ┆         ┆          ┆                 │
│ ok20ary_2026-01-07        ┆            ┆              ┆         ┆   ┆         ┆         ┆          ┆                 │
│ sprzedam działkę          ┆ 2025-11-24 ┆ 2025-11-29   ┆ 0.0     ┆ … ┆ 53.1539 ┆ 22.6653 ┆ null     ┆ analyzed_offers │
│ budowlaną w_2025-11-23    ┆            ┆              ┆         ┆   ┆         ┆         ┆          ┆                 │
└───────────────────────────┴────────────┴──────────────┴─────────┴───┴─────────┴─────────┴──────────┴─────────────────┘

## Day of the week mapping

In [106]:
week_days = {
    1: "Poniedziałek",
    2: "Wtorek",
    3: "Środa",
    4: "Czwartek",
    5: "Piątek",
    6: "Sobota",
    7: "Niedziela"
}

In [108]:
data["Offers_all"] = data["Offers_all"].with_columns([
    pl.col("DATE_ADDED").cast(pl.Date),
    pl.col("DATE_ADDED")
    .dt.weekday()
    .cast(pl.String) 
    .replace(week_days)
    .alias("DAY_NAME_PL")
])

## Cleaning AREA_M2

In [110]:
data["Offers_all"] = data["Offers_all"].with_columns(
    pl.when(pl.col("AREA_M2") <= 1.0)
    .then(None)
    .otherwise(pl.col("AREA_M2"))
    .alias("AREA_M2")
)

In [113]:
data["Offers_all"] = data["Offers_all"].with_columns([
    pl.when(pl.col("AREA_M2") < 100.0)
    .then(pl.col("AREA_M2") * 100.0)
    .otherwise(pl.col("AREA_M2"))
    .alias("AREA_M2")
]).with_columns([
    pl.when(pl.col("AREA_M2") < 100.0)
    .then(None)
    .otherwise(pl.col("AREA_M2"))
    .alias("AREA_M2")
]).with_columns([
    pl.when((pl.col("PRICE").is_not_null()) & (pl.col("AREA_M2").is_not_null()))
    .then(pl.col("PRICE") / pl.col("AREA_M2"))
    .otherwise(None)
    .alias("PRICE_M2")
])
print(data["Offers_all"].filter(pl.col("ID").str.contains("MORGOWNIKI|NOWOGRÓD|Zawady_10")).select([
    "ID", "AREA_M2", "PRICE", "PRICE_M2"
]))

shape: (2, 4)
┌────────────────────┬─────────┬──────────┬──────────┐
│ ID                 ┆ AREA_M2 ┆ PRICE    ┆ PRICE_M2 │
│ ---                ┆ ---     ┆ ---      ┆ ---      │
│ str                ┆ f64     ┆ f64      ┆ f64      │
╞════════════════════╪═════════╪══════════╪══════════╡
│ Zawady_1000_130000 ┆ 1000.0  ┆ 130000.0 ┆ 130.0    │
│ Zawady_10_89000    ┆ 1000.0  ┆ 89000.0  ┆ 89.0     │
└────────────────────┴─────────┴──────────┴──────────┘

In [119]:
data["Offers_all"] = data["Offers_all"].with_columns(
    pl.when(pl.col("ID") == "dzialka-jedwabne-lomzynska")
    .then(pl.lit(10200.0))
    .otherwise(pl.col("AREA_M2"))
    .alias("AREA_M2")
)

data["Offers_all"] = data["Offers_all"].with_columns(
    pl.when(pl.col("ID") == "dzialka-jedwabne-lomzynska")
    .then(pl.col("PRICE") / pl.col("AREA_M2"))
    .otherwise(pl.col("PRICE_M2"))
    .alias("PRICE_M2")
)

In [120]:
data["Offers_all"]

shape: (636, 11)
┌──────────────────────┬────────────┬──────────────┬─────────┬───┬─────────┬──────────┬─────────────────┬──────────────┐
│ ID                   ┆ DATE_ADDED ┆ LAST_UPDATED ┆ AREA_M2 ┆ … ┆ LON     ┆ PRICE    ┆ SOURCE          ┆ DAY_NAME_PL  │
│ ---                  ┆ ---        ┆ ---          ┆ ---     ┆   ┆ ---     ┆ ---      ┆ ---             ┆ ---          │
│ str                  ┆ date       ┆ date         ┆ f64     ┆   ┆ f64     ┆ f64      ┆ str             ┆ str          │
╞══════════════════════╪════════════╪══════════════╪═════════╪═══╪═════════╪══════════╪═════════════════╪══════════════╡
│ Łomża_2134_99000     ┆ 2025-11-10 ┆ 2025-11-11   ┆ 2134.0  ┆ … ┆ 22.0592 ┆ 99000.0  ┆ offers          ┆ Poniedziałek │
│ Zawady_1000_130000   ┆ 2026-02-11 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ 22.6653 ┆ 130000.0 ┆ offers          ┆ Środa        │
│ Elżbiecin_12200_1490 ┆ 2026-02-10 ┆ 2025-11-11   ┆ 12200.0 ┆ … ┆ 22.1231 ┆ 1.49e6   ┆ offers          ┆ Wtorek       │
│ 000                  ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ Jurki_3000_67500     ┆ 2025-11-06 ┆ 2025-11-11   ┆ 3000.0  ┆ … ┆ 22.1114 ┆ 67500.0  ┆ offers          ┆ Czwartek     │
│ Łomża_1000_129500    ┆ 2025-11-06 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ 22.0592 ┆ 129500.0 ┆ offers          ┆ Czwartek     │
│ …                    ┆ …          ┆ …            ┆ …       ┆ … ┆ …       ┆ …        ┆ …               ┆ …            │
│ na sprzedaż działka  ┆ 2026-02-06 ┆ 2026-02-12   ┆ 1054.0  ┆ … ┆ 21.8806 ┆ null     ┆ analyzed_offers ┆ Piątek       │
│ budowlana_2026-02-05 ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ sprzedam działkę     ┆ 2026-02-18 ┆ 2026-02-18   ┆ null    ┆ … ┆ 21.8806 ┆ null     ┆ analyzed_offers ┆ Środa        │
│ budowlaną            ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ w_2026-02-17         ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ na sprzedaż          ┆ 2026-02-06 ┆ 2026-02-12   ┆ 505.0   ┆ … ┆ 22.0592 ┆ null     ┆ analyzed_offers ┆ Piątek       │
│ atrakcyjna           ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ działka_2026-02-05   ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ sprzedam działkę     ┆ 2026-01-08 ┆ 2026-01-14   ┆ null    ┆ … ┆ 22.1486 ┆ null     ┆ analyzed_offers ┆ Czwartek     │
│ budowlaną            ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ ok20ary_2026-01-07   ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ sprzedam działkę     ┆ 2025-11-24 ┆ 2025-11-29   ┆ null    ┆ … ┆ 22.6653 ┆ null     ┆ analyzed_offers ┆ Poniedziałek │
│ budowlaną            ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
│ w_2025-11-23         ┆            ┆              ┆         ┆   ┆         ┆          ┆                 ┆              │
└──────────────────────┴────────────┴──────────────┴─────────┴───┴─────────┴──────────┴─────────────────┴──────────────┘

## Measuring distance from main_city

In [136]:
LOMZA_LAT = 53.1781
LOMZA_LON = 22.0592
data["Offers_all"] = add_haversine_distance(data["Offers_all"], LOMZA_LAT, LOMZA_LON)

In [137]:
data["Offers_all"]

shape: (636, 12)
┌────────────────┬────────────┬──────────────┬─────────┬───┬──────────┬────────────────┬──────────────┬────────────────┐
│ ID             ┆ DATE_ADDED ┆ LAST_UPDATED ┆ AREA_M2 ┆ … ┆ PRICE    ┆ SOURCE         ┆ DAY_NAME_PL  ┆ MAIN_CITY_DIST │
│ ---            ┆ ---        ┆ ---          ┆ ---     ┆   ┆ ---      ┆ ---            ┆ ---          ┆ ---            │
│ str            ┆ date       ┆ date         ┆ f64     ┆   ┆ f64      ┆ str            ┆ str          ┆ f64            │
╞════════════════╪════════════╪══════════════╪═════════╪═══╪══════════╪════════════════╪══════════════╪════════════════╡
│ Łomża_2134_990 ┆ 2025-11-10 ┆ 2025-11-11   ┆ 2134.0  ┆ … ┆ 99000.0  ┆ offers         ┆ Poniedziałek ┆ 0.0            │
│ 00             ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ Zawady_1000_13 ┆ 2026-02-11 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ 130000.0 ┆ offers         ┆ Środa        ┆ 40.492747      │
│ 0000           ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ Elżbiecin_1220 ┆ 2026-02-10 ┆ 2025-11-11   ┆ 12200.0 ┆ … ┆ 1.49e6   ┆ offers         ┆ Wtorek       ┆ 4.428093       │
│ 0_1490000      ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ Jurki_3000_675 ┆ 2025-11-06 ┆ 2025-11-11   ┆ 3000.0  ┆ … ┆ 67500.0  ┆ offers         ┆ Czwartek     ┆ 24.729752      │
│ 00             ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ Łomża_1000_129 ┆ 2025-11-06 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ 129500.0 ┆ offers         ┆ Czwartek     ┆ 0.0            │
│ 500            ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ …              ┆ …          ┆ …            ┆ …       ┆ … ┆ …        ┆ …              ┆ …            ┆ …              │
│ na sprzedaż    ┆ 2026-02-06 ┆ 2026-02-12   ┆ 1054.0  ┆ … ┆ null     ┆ analyzed_offer ┆ Piątek       ┆ 13.05184       │
│ działka budowl ┆            ┆              ┆         ┆   ┆          ┆ s              ┆              ┆                │
│ ana_2026-02-05 ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ sprzedam       ┆ 2026-02-18 ┆ 2026-02-18   ┆ null    ┆ … ┆ null     ┆ analyzed_offer ┆ Środa        ┆ 13.05184       │
│ działkę        ┆            ┆              ┆         ┆   ┆          ┆ s              ┆              ┆                │
│ budowlaną      ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ w_2026-02-17   ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ na sprzedaż    ┆ 2026-02-06 ┆ 2026-02-12   ┆ 505.0   ┆ … ┆ null     ┆ analyzed_offer ┆ Piątek       ┆ 0.0            │
│ atrakcyjna dzi ┆            ┆              ┆         ┆   ┆          ┆ s              ┆              ┆                │
│ ałka_2026-02-0 ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ 5              ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ sprzedam       ┆ 2026-01-08 ┆ 2026-01-14   ┆ null    ┆ … ┆ null     ┆ analyzed_offer ┆ Czwartek     ┆ 6.273334       │
│ działkę        ┆            ┆              ┆         ┆   ┆          ┆ s              ┆              ┆                │
│ budowlaną ok20 ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ ary_2026-01-07 ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ sprzedam       ┆ 2025-11-24 ┆ 2025-11-29   ┆ null    ┆ … ┆ null     ┆ analyzed_offer ┆ Poniedziałek ┆ 40.492747      │
│ działkę        ┆            ┆              ┆         ┆   ┆          ┆ s              ┆              ┆                │
│ budowlaną      ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
│ w_2025-11-23   ┆            ┆              ┆         ┆   ┆          ┆                ┆              ┆                │
└────────────────┴────────────┴──────────────┴─────────┴───┴──────────┴────────────────┴──────────────┴────────────────┘

## Size segments

In [139]:
size_bins = [700.0, 1000.0, 1500.0, 5000.0, 10000.0]

size_labels = [
    "Tiny/Sub-standard",    
    "Small Plot",           
    "Medium Plot",         
    "Large Plot",           
    "Investment/Small Farm",
    "Hectares/Agriculture" 
]

data["Offers_all"] = data["Offers_all"].with_columns(
    pl.col("AREA_M2").cut(
        size_bins, 
        labels=size_labels
    ).alias("SIZE_SEGMENT")
)

In [140]:
data["Offers_all"]

shape: (636, 13)
┌───────────────┬────────────┬──────────────┬─────────┬───┬───────────────┬──────────────┬──────────────┬──────────────┐
│ ID            ┆ DATE_ADDED ┆ LAST_UPDATED ┆ AREA_M2 ┆ … ┆ SOURCE        ┆ DAY_NAME_PL  ┆ MAIN_CITY_DI ┆ SIZE_SEGMENT │
│ ---           ┆ ---        ┆ ---          ┆ ---     ┆   ┆ ---           ┆ ---          ┆ ST           ┆ ---          │
│ str           ┆ date       ┆ date         ┆ f64     ┆   ┆ str           ┆ str          ┆ ---          ┆ cat          │
│               ┆            ┆              ┆         ┆   ┆               ┆              ┆ f64          ┆              │
╞═══════════════╪════════════╪══════════════╪═════════╪═══╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ Łomża_2134_99 ┆ 2025-11-10 ┆ 2025-11-11   ┆ 2134.0  ┆ … ┆ offers        ┆ Poniedziałek ┆ 0.0          ┆ Large Plot   │
│ 000           ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ Zawady_1000_1 ┆ 2026-02-11 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ offers        ┆ Środa        ┆ 40.492747    ┆ Small Plot   │
│ 30000         ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ Elżbiecin_122 ┆ 2026-02-10 ┆ 2025-11-11   ┆ 12200.0 ┆ … ┆ offers        ┆ Wtorek       ┆ 4.428093     ┆ Hectares/Agr │
│ 00_1490000    ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆ iculture     │
│ Jurki_3000_67 ┆ 2025-11-06 ┆ 2025-11-11   ┆ 3000.0  ┆ … ┆ offers        ┆ Czwartek     ┆ 24.729752    ┆ Large Plot   │
│ 500           ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ Łomża_1000_12 ┆ 2025-11-06 ┆ 2025-11-11   ┆ 1000.0  ┆ … ┆ offers        ┆ Czwartek     ┆ 0.0          ┆ Small Plot   │
│ 9500          ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ …             ┆ …          ┆ …            ┆ …       ┆ … ┆ …             ┆ …            ┆ …            ┆ …            │
│ na sprzedaż   ┆ 2026-02-06 ┆ 2026-02-12   ┆ 1054.0  ┆ … ┆ analyzed_offe ┆ Piątek       ┆ 13.05184     ┆ Medium Plot  │
│ działka budow ┆            ┆              ┆         ┆   ┆ rs            ┆              ┆              ┆              │
│ lana_2026-02- ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ 05            ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ sprzedam      ┆ 2026-02-18 ┆ 2026-02-18   ┆ null    ┆ … ┆ analyzed_offe ┆ Środa        ┆ 13.05184     ┆ null         │
│ działkę       ┆            ┆              ┆         ┆   ┆ rs            ┆              ┆              ┆              │
│ budowlaną     ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ w_2026-02-17  ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ na sprzedaż   ┆ 2026-02-06 ┆ 2026-02-12   ┆ 505.0   ┆ … ┆ analyzed_offe ┆ Piątek       ┆ 0.0          ┆ Tiny/Sub-sta │
│ atrakcyjna    ┆            ┆              ┆         ┆   ┆ rs            ┆              ┆              ┆ ndard        │
│ działka_2026- ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ 02-05         ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ sprzedam      ┆ 2026-01-08 ┆ 2026-01-14   ┆ null    ┆ … ┆ analyzed_offe ┆ Czwartek     ┆ 6.273334     ┆ null         │
│ działkę       ┆            ┆              ┆         ┆   ┆ rs            ┆              ┆              ┆              │
│ budowlaną ok2 ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ 0ary_2026-01- ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ 07            ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ sprzedam      ┆ 2025-11-24 ┆ 2025-11-29   ┆ null    ┆ … ┆ analyzed_offe ┆ Poniedziałek ┆ 40.492747    ┆ null         │
│ działkę       ┆            ┆              ┆         ┆   ┆ rs            ┆              ┆              ┆              │
│ budowlaną     ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
│ w_2025-11-23  ┆            ┆              ┆         ┆   ┆               ┆              ┆              ┆              │
└───────────────┴────────────┴──────────────┴─────────┴───┴───────────────┴──────────────┴──────────────┴──────────────┘